# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2274fa46440f96894c2d5a779fba9775136850832b17ca4da4782de5a2a7949e777151c7a662e6e798063513f1c657d49019f14d822df1b78e5f92c008ae3e6d

test:
  secret_key_base: aeee897877754d2320ea0c4dfbff2f24fc963ed1665684d3e8b371ff7a33fef11469833ba37754f6a7ac26300e2c50d4eceb0f9a89fe40d707bb8ffa36b6d313

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
